Repository lifinance/widget, pull requests merged in 2024-07, with the labels that each got.

#260 feat!: remove insurance
  packages/widget/src/components/Card/CardLabel.tsx
  packages/widget/src/components/Insurance/Insurance.tsx
  packages/widget/src/components/Insurance/InsuranceCard.tsx
  packages/widget/src/components/Insurance/InsuranceCollapsed.tsx
  packages/widget/src/components/Insurance/types.ts
  packages/widget/src/components/RouteCard/RouteCard.tsx
  packages/widget/src/hooks/useRoutes.ts
  packages/widget/src/i18n/en.json
  packages/widget/src/icons/InsuraceLogo.tsx
  packages/widget/src/pages/TransactionDetailsPage/TransactionDetailsPage.tsx
  packages/widget/src/pages/TransactionPage/StartTransactionButton.tsx
  packages/widget/src/pages/TransactionPage/TransactionPage.tsx
  packages/widget/src/pages/TransactionPage/types.ts
  packages/widget/src/stores/routes/createRouteExecutionStore.ts
  packages/widget/src/stores/routes/types.ts
  packages/widget/src/types/widget.ts
Labels: WIP, wait

#267 fix: json assertions
  examples/create-react-app/.babelrc
  examples/create-react-app/README.md
  examples/create-react-app/config-overrides.js
  examples/create-react-app/package.json
  examples/create-react-app/yarn.lock
  examples/nextjs-page-router/README.md
  examples/nextjs-page-router/app/favicon.ico
  examples/nextjs-page-router/app/globals.css
  examples/nextjs-page-router/app/layout.tsx
  examples/nextjs-page-router/app/page.tsx
  examples/nextjs-page-router/components/ClientOnly.tsx
  examples/nextjs-page-router/components/DynamicImportWidget.tsx
  examples/nextjs-page-router/components/Widget.tsx
  examples/nextjs-page-router/hooks/useHydrated.ts
  examples/nextjs-page-router/next.config.js
  examples/nextjs-page-router/pages/dynamic-import.tsx
  examples/nextjs-page-router/pages/index.tsx
  examples/nextjs-page-router/pages/pages-example.tsx
  examples/nextjs-page-router/styles/Home.module.css
  examples/nextjs/README.md
  examples/nextjs/app/page.module.css
  examples/nextjs/components/PagesWidget.tsx
  examples/nextjs/next.config.js
  examples/nextjs/pages/_app.tsx
  examples/nextjs/pages/_document.tsx
  examples/nextjs/pages/dynamic-import.tsx
  examples/nextjs/pages/pages-example.tsx
  examples/nextjs/styles/globals.css
  examples/nextjs/tsconfig.json
  examples/remix/app/components/Fallback.tsx
  examples/remix/app/components/LiFiWidget.tsx
  examples/remix/app/routes/$.tsx
  examples/remix/app/routes/_index.tsx
  examples/vite/src/components/WalletHeader.tsx
  packages/widget/src/components/Step/StepTimer.tsx
  packages/widget/src/i18n/i18next.d.ts
  packages/widget/src/i18n/index.ts
Labels: WIP

#270 refactor: use widgets own timer hook
  packages/widget/package.json
  packages/widget/src/components/Step/StepTimer.tsx
  packages/widget/src/hooks/timer/useInterval.ts
  packages/widget/src/hooks/timer/useTimer.ts
  packages/widget/src/hooks/timer/utils.ts
  yarn.lock
Labels: testing

#268 feat: improve review page with route tracker, added new fee card and improved route card
  packages/widget/src/components/Card/CardIconButton.tsx
  packages/widget/src/components/ChainSelect/ChainSelect.tsx
  packages/widget/src/components/FeeBreakdownTooltip.tsx
  packages/widget/src/components/Header/CloseDrawerButton.tsx
  packages/widget/src/components/Header/SettingsButton.tsx
  packages/widget/src/components/Header/TransactionHistoryButton.tsx
  packages/widget/src/components/IconTypography.ts
  packages/widget/src/components/PoweredBy/PoweredBy.tsx
  packages/widget/src/components/ProgressToNextUpdate.tsx
  packages/widget/src/components/RouteCard/RouteCard.style.ts
  packages/widget/src/components/RouteCard/RouteCard.tsx
  packages/widget/src/components/RouteCard/RouteCardEssentials.tsx
  packages/widget/src/components/RouteCard/RouteCardEssentialsExpanded.tsx
  packages/widget/src/components/RouteCard/types.ts
  packages/widget/src/components/Routes/RoutesExpanded.tsx
  packages/widget/src/components/SendToWallet/SendToWalletExpandButton.tsx
  packages/widget/src/components/Step/Step.tsx
  packages/widget/src/components/Step/StepList.tsx
  packages/widget/src/components/Step/StepTimer.tsx
  packages/widget/src/components/StepActions/StepActions.tsx
  packages/widget/src/components/StepActions/StepFeeBreakdown.tsx
  packages/widget/src/components/Token/Token.style.tsx
  packages/widget/src/components/Token/Token.tsx
  packages/widget/src/components/TokenRate.tsx
  packages/widget/src/components/TransactionDetails.tsx
  packages/widget/src/hooks/useAvailableChains.ts
  packages/widget/src/hooks/useGasRecommendation.ts
  packages/widget/src/hooks/useRoutes.ts
  packages/widget/src/hooks/useTokens.ts
  packages/widget/src/hooks/useTools.ts
  packages/widget/src/hooks/useTransactionDetails.ts
  packages/widget/src/hooks/useTransactionHistory.ts
  packages/widget/src/i18n/en.json
  packages/widget/src/pages/MainPage/ReviewButton.tsx
  packages/widget/src/pages/RoutesPage/RoutesPage.tsx
  packages/widget/src/pages/SelectEnabledToolsPage.tsx
  packages/widget/src/pages/SendToWallet/SendToWalletPage.tsx
  packages/widget/src/pages/SettingsPage/ThemeSettings.tsx
  packages/widget/src/pages/TransactionDetailsPage/TransactionDetailsPage.tsx
  packages/widget/src/pages/TransactionHistoryPage/TransactionHistoryItem.tsx
  packages/widget/src/pages/TransactionPage/ExchangeRateBottomSheet.tsx
  packages/widget/src/pages/TransactionPage/RouteTracker.tsx
  packages/widget/src/pages/TransactionPage/TransactionPage.tsx
  packages/widget/src/providers/I18nProvider/I18nProvider.tsx
  packages/widget/src/providers/I18nProvider/currencyExtendedFormatter.ts
  packages/widget/src/stores/routes/createRouteExecutionStore.ts
  packages/widget/src/stores/routes/types.ts
  packages/widget/src/themes/createTheme.ts
  packages/widget/src/utils/converters.ts
  packages/widget/src/utils/fees.ts
  packages/widget/src/utils/format.ts
Labels: testing

#275 chore: bump packages
  package.json
  packages/wallet-management/package.json
  packages/widget-embedded/package.json
  packages/widget-playground-next/package.json
  packages/widget-playground-vite/package.json
  packages/widget-playground/package.json
  packages/widget-playground/src/defaultWidgetConfig.ts
  packages/widget/package.json
  yarn.lock
Labels: testing

#278 feat: improve the display of estimated duration and fees
  packages/widget/src/components/ActiveTransactions/ActiveTransactionItem.tsx
  packages/widget/src/components/Card/CardIconButton.tsx
  packages/widget/src/components/FeeBreakdownTooltip.tsx
  packages/widget/src/components/IconTypography.ts
  packages/widget/src/components/RouteCard/RouteCardEssentials.tsx
  packages/widget/src/components/Step/DestinationWalletAddress.tsx
  packages/widget/src/components/Step/Step.tsx
  packages/widget/src/components/Step/StepProcess.style.tsx
  packages/widget/src/components/Step/StepProcess.tsx
  packages/widget/src/components/Step/StepTimer.tsx
  packages/widget/src/components/StepActions/StepActions.style.tsx
  packages/widget/src/components/TransactionDetails.tsx
  packages/widget/src/hooks/timer/useTimer.ts
  packages/widget/src/i18n/en.json
  packages/widget/src/pages/TransactionDetailsPage/TransactionDetailsPage.tsx
  packages/widget/src/pages/TransactionPage/TokenValueBottomSheet.tsx
  packages/widget/src/pages/TransactionPage/TransactionPage.tsx
  packages/widget/src/pages/TransactionPage/utils.ts
  packages/widget/src/stores/routes/types.ts
  packages/widget/src/types/events.ts
  packages/widget/src/utils/converters.ts
  packages/widget/src/utils/fees.ts
Labels: testing
